{"id":"google/cloud/error","name":"Error","title":["Google","Cloud","Error"],"description":"<p>Base google-cloud exception class.</p>","source":"google-cloud-core/lib/google/cloud/errors.rb#L22","resources":[],"examples":[],"methods":[{"id":"initialize-constructor","type":"constructor","name":"initialize","title":["Google","Cloud","Error#initialize"],"description":"<p>Construct a new Google::Cloud::Error object, optionally passing in a\nmessage.</p>","source":"google-cloud-core/lib/google/cloud/errors.rb#L26","resources":[],"examples":[],"params":[],"exceptions":[],"returns":[{"types":["<a data-custom-type=\"google/cloud/error\">Error</a>"],"description":"a new instance of Error"}]},{"id":"cause-instance","type":"instance","name":"cause","title":["Google","Cloud","Error#cause"],"description":"<p>The previous exception at the time this exception was raised. This is\nuseful for wrapping exceptions and retaining the original exception\ninformation.</p>","source":"google-cloud-core/lib/google/cloud/errors.rb#L37","resources":[],"examples":[],"params":[],"exceptions":[],"returns":[]},{"id":"status_code-instance","type":"instance","name":"status_code","title":["Google","Cloud","Error#status_code"],"description":"<p>Returns the value of <code>status_code</code> from the underlying cause error\nobject, if both are present. Otherwise returns <code>nil</code>.</p>\n\n<p>This is typically present on errors originating from calls to an API\nover HTTP/REST.</p>","source":"google-cloud-core/lib/google/cloud/errors.rb#L50","resources":[],"examples":[],"params":[],"exceptions":[],"returns":[{"types":["Object","nil"],"description":""}]},{"id":"body-instance","type":"instance","name":"body","title":["Google","Cloud","Error#body"],"description":"<p>Returns the value of <code>body</code> from the underlying cause error\nobject, if both are present. Otherwise returns <code>nil</code>.</p>\n\n<p>This is typically present on errors originating from calls to an API\nover HTTP/REST.</p>","source":"google-cloud-core/lib/google/cloud/errors.rb#L63","resources":[],"examples":[],"params":[],"exceptions":[],"returns":[{"types":["Object","nil"],"description":""}]},{"id":"header-instance","type":"instance","name":"header","title":["Google","Cloud","Error#header"],"description":"<p>Returns the value of <code>header</code> from the underlying cause error\nobject, if both are present. Otherwise returns <code>nil</code>.</p>\n\n<p>This is typically present on errors originating from calls to an API\nover HTTP/REST.</p>","source":"google-cloud-core/lib/google/cloud/errors.rb#L76","resources":[],"examples":[],"params":[],"exceptions":[],"returns":[{"types":["Object","nil"],"description":""}]},{"id":"code-instance","type":"instance","name":"code","title":["Google","Cloud","Error#code"],"description":"<p>Returns the value of <code>code</code> from the underlying cause error\nobject, if both are present. Otherwise returns <code>nil</code>.</p>\n\n<p>This is typically present on errors originating from calls to an API\nover gRPC.</p>","source":"google-cloud-core/lib/google/cloud/errors.rb#L89","resources":[],"examples":[],"params":[],"exceptions":[],"returns":[{"types":["Object","nil"],"description":""}]},{"id":"details-instance","type":"instance","name":"details","title":["Google","Cloud","Error#details"],"description":"<p>Returns the value of <code>details</code> from the underlying cause error\nobject, if both are present. Otherwise returns <code>nil</code>.</p>\n\n<p>This is typically present on errors originating from calls to an API\nover gRPC.</p>","source":"google-cloud-core/lib/google/cloud/errors.rb#L102","resources":[],"examples":[],"params":[],"exceptions":[],"returns":[{"types":["Object","nil"],"description":""}]},{"id":"metadata-instance","type":"instance","name":"metadata","title":["Google","Cloud","Error#metadata"],"description":"<p>Returns the value of <code>metadata</code> from the underlying cause error\nobject, if both are present. Otherwise returns <code>nil</code>.</p>\n\n<p>This is typically present on errors originating from calls to an API\nover gRPC.</p>","source":"google-cloud-core/lib/google/cloud/errors.rb#L115","resources":[],"examples":[],"params":[],"exceptions":[],"returns":[{"types":["Object","nil"],"description":""}]},{"id":"status_details-instance","type":"instance","name":"status_details","title":["Google","Cloud","Error#status_details"],"description":"<p>Returns the value of <code>status_details</code> from the underlying cause error\nobject, if both are present. Otherwise returns <code>nil</code>.</p>\n\n<p>This is typically present on errors originating from calls to an API\nover gRPC.</p>","source":"google-cloud-core/lib/google/cloud/errors.rb#L128","resources":[],"examples":[],"params":[],"exceptions":[],"returns":[{"types":["Object","nil"],"description":""}]}]}